- appsec-kit-backend/pom.xml
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecConfiguration.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecException.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecService.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/AppSecData.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecConfigurationTest.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecServiceTest.java
- pom.xml
This adds the `AppSecService` class with data storage capabilities to save persistent informations about the vulnerability analysis onto the file-system.
Closes #26
> Add service and data storage to the backend module

- appsec-kit-demo-v8/src/main/java/com/vaadin/appsec/demo/util/OpenSourceVulnerabilityUtils.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/service/AppSecDataProvider.java
Version check fixes duplicate vulnerabilities in the grid.
> Added affected version check. Prefer CVE* for id if present.

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecService.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/service/AppSecKitInitializer.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/service/NotificationInitializer.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/AppSecUI.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/MainView.java
- appsec-kit-v7/src/test/java/com/vaadin/appsec/v7/service/AppSecKitInitializerTest.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/service/AppSecServiceInitListener.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/service/NotificationInitListener.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/AppSecUI.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/MainView.java
- appsec-kit-v8/src/test/java/com/vaadin/appsec/v8/service/AppSecServiceInitListenerTest.java
This fixes an issue with session access that might prevent notifications to show up on some UIs. It also improves the content of the notification message to include more informations.
> Improve notification content and fix session access

- README.md
> Add README file for AppSec Kit

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecConfiguration.java
Handle exceptions when getting the SBOM file. Also, some web and application servers can use file systems which are not supported, in these cases the SBOM file's relative path is returned.
> Fix getting SBOM file path

- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/VulnerabilityDetailsView.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/VulnerabilityDetailsView.java
This PR fixes a NPE when getting the assessments for a vulnerability and there is no analysis for the vulnerability.
> Fix NPE when getting assessments

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/dto/Vulnerability.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/VulnerabilityDetailsView.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/VulnerabilityDetailsView.java
> Show vulnerable and fixed versions on dependency details view

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/analysis/AssessmentStatus.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/dto/Vulnerability.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/AbstractAppSecContent.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/VulnerabilitiesTab.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/VulnerabilityDetailsView.java
- appsec-kit-v7/src/main/resources/com/vaadin/appsec/v7/ui/appsec-v7.css
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/VulnerabilitiesTab.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/VulnerabilityDetailsView.java
- appsec-kit-v8/src/main/resources/com/vaadin/appsec/v8/ui/appsec-v8.css
Shows Vaadin analysis assessment status on the Vulnerabilities tab and adds filter option for it.
Closes #64
> Show Vaadin analysis and add filter option for it

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java
- pom.xml
> Add connect/read timeouts for OSV API

- appsec-kit-backend/pom.xml
- appsec-kit-demo-v24-spring/pom.xml
- appsec-kit-demo-v7/pom.xml
- appsec-kit-demo-v8-cdi/pom.xml
- appsec-kit-demo-v8-spring/pom.xml
- appsec-kit-demo-v8/pom.xml
- appsec-kit-v24/pom.xml
- appsec-kit-v7/pom.xml
- appsec-kit-v8/pom.xml
- pom.xml
Bump to 1.1-SNAPSHOT before releasing 1.1.0
> Bump to 1.1-SNAPSHOT

- README.md
- Adds V24 documentation link to the main README
> Add V24 documentation link to the main README

- pom.xml
Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)
> chore: update vaadin-parent to 2.2.1

- .gitignore
> cp: chore: add Vaadin auto-generated files to .gitignore (#135)

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecConfiguration.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java
- appsec-kit-starter/src/test/java/com/vaadin/appsec/service/AppSecServiceInitListenerTest.java
> Check for push when AppSec UI is initialized

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecService.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/VulnerabilityStore.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java
If the OSV API throws an `IOException`, make sure that we at least log the error and don't break the AppSec Kit starter UI.
Fixes #124
> fix: Handle exceptions

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecConfiguration.java
- appsec-kit-demo/src/main/java/com/vaadin/appsec/demo/MainView.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java
- appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java
- appsec-kit-starter/src/test/java/com/vaadin/appsec/service/AppSecServiceInitListenerTest.java
Backporting solution #136 created for #132 to 2.0 version.
In AppSec Kit 2.0 for v14 and V23 version there is a notification dialog shown when vulnerabilities are found, therefore the push mode is enabled for each UI to be able to show the dialog.
> Add check for push when a UI is initialized

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecService.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/VulnerabilityStore.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/service/AppSecKitInitializer.java
- appsec-kit-v7/src/main/java/com/vaadin/appsec/v7/ui/content/AppSecView.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/service/AppSecServiceInitListener.java
- appsec-kit-v8/src/main/java/com/vaadin/appsec/v8/ui/content/AppSecView.java
Cherry pick of #133 
Fixes #124
> CP: fix: handle exceptions

- appsec-kit-backend/pom.xml
- appsec-kit-demo/pom.xml
- Updates `cyclonedx-core-java` dependency version to 8.0.3
- Updates `cyclonedx-maven-plugin` to 2.8.0 in demo app
- Updates CycloneDX schema version to 1.5 in demo app
- Adds spec version to `cyclonedx-npm` plugin in demo app
> Update cyclonedx-core-java dependency to 8.0.3

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecDTOProviderTest.java
Filter out affected elements with unsupported ecosystem when getting the vulnerabilities.
Fixes #173
> Filter out affected elements with unsupported ecosystem

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecDTOProviderTest.java
Filter out affected elements with unsupported ecosystem when getting the vulnerabilities.
> Filter out affected elements with unsupported ecosystem [1.0]

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecDTOProviderTest.java
Filter out affected elements with unsupported ecosystem when getting the vulnerabilities.
> Filter out affected elements with unsupported ecosystem [2.0]

- appsec-kit-backend/pom.xml
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/AppSecData.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/osv/response/Severity.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecDTOProviderTest.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/BillOfMaterialsStoreTest.java
- appsec-kit-backend/src/test/resources/bom.json
> fix: Add missing enum value

- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/AppSecDTOProvider.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/AppSecData.java
- appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/model/osv/response/Severity.java
- appsec-kit-backend/src/test/java/com/vaadin/appsec/backend/AppSecDTOProviderTest.java
> Add check for supported CVSS versions

- appsec-kit-starter/src/main/java/com/vaadin/appsec/service/LicenseCheckerServiceInitListener.java
- pom.xml
> cp: use BaseLicenseCheckerServiceInitListener as super class to LicenseCheckerServiceInitListener

- appsec-kit-backend/pom.xml
- appsec-kit-demo/pom.xml
- appsec-kit-starter/pom.xml
- appsec-kit-starter/src/test/java/com/vaadin/appsec/service/LicenseCheckerServiceInitListenerTest.java
- pom.xml
> Bump to 3.4-SNAPSHOT
